spring:
  devtools:
    restart:
      enabled: true
  mustache:
    cache: false
    expose-session-attributes: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
